### ISSUE TITLE
Модель резюме

### ISSUE THREAD

**Issue by Sula19** [nurmuhamedbekinulu/team_dev_hh_group_9#9]
Резюме 

    Для чего это нужно : Требования ТЗ

    Как это сделать: Возможность создания резюме. Ниже приведен пример разделения и основные модули для резюме. Здесь стоит разобраться немного подробнее:

    Есть основная часть резюме т.е базовая информация о пользователе, где пользователь выбирает категорию вакансии, задает название резюме (должности) ожидаемый уровень заработной платы, и указывает ссылки на соцсети, контактные данные :
    p.s если какие то данные не указаны то не нужно отображать их на странице при просмотре резюме.

        telegram

        email

        номер телефона

        ссылка на Facebook

        ссылка на Linkedin

    Так же есть множество однотипных модулей которые связаны с основным резюме. В ходе создания резюме вы можете добавить неограниченное количество таких модулей. Каждый из них должен описывать опыт работы.  Годы работы, название компании, должность, обязанности.

    Аналогичные модули для указания образования соискателя или же пройденных курсов повышения квалификации.

Возможность редактирования резюме. А также его обновления, по нажатию на кнопку обновить, обновляется только его дата обновления, по сути то же что и при редактировании.

Возможность публикации резюме и его снятия с публичного просмотра. если резюме не опубликовано оно не будет отображаться в общем списке.

    Критерии приема :  Соискатель может создать резюме и опубликовать его

    Планируемое время : 5 часов

**Comment by Nikelea** [comment]
Затраченно 4 часа. Не доделаны допольнительные модули
